version: '3'

services:
  lavaboard:
    build: ./lavaboard/
    container_name: lavaboard
    ports:
      - 80:80
    restart: always
    environment:
      - 0.0.0.0
  server:
    build:  ./server
    container_name: server
    ports:
      - 8080:8080
    restart: always
    environment:
      - 0.0.0.0
  db:
    image: mongo
    container_name: mongo-db
    restart: always
    volumes:
      - "mongodata:/data/db"
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  mongo-express:    
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo-db

volumes:
  mongodata: